spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: minchina91
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8888
mybatis:
  config-location: classpath:mybatis-config.xml