spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: minchina91
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true

server:
  port: 8888
mybatis:
  config-location: classpath:mybatis-config.xml
github:
  token:
    url: https://github.com/login/oauth/access_token
  userInfo:
    url: https://api.github.com/user?access_token=
  client_id: 2ba17e439c0a95084861
  client_secrect: 92b9a120df1765117e03c396b06a03f0ef208505