spring:
  datasource:
    url: jdbc:hsqldb:mem:todomvc;sql.syntax_ora=true
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      local: false
      properties:
        transport:
          tcp:
            connect_timeout: 60s
  jpa:
    generate-ddl: true

server:
  port: 8888
mybatis:
  config-location: classpath:mybatis-config.xml
github:
  token:
    url: https://github.com/login/oauth/access_token
  userInfo:
    url: https://api.github.com/user?access_token=
  client_id: 2ba17e439c0a95084861
  client_secrect: 92b9a120df1765117e03c396b06a03f0ef208505
